config/routes.rb
Bottleservice::Application.routes.draw do
  resources :orders

  devise_for :members
  devise_for :drivers
  resources :comments

  resources :drivers

  
  resources :products

  root 'orders#new'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  # GET /products
  # GET /products.json
  def index
    
  end

  def update_quantities(params)
    order = Order.find(params[:id])
    order.update_quantity #call your method on the model to update the username
    redirect_to :back #or whatever you'd like it to redirect to
  end
  helper_method :update_quantities

end

app/controllers/homes_controller.rb
class HomeController < ApplicationController
  @@this_week = [1,2]

  # GET /products
  # GET /products.json
  def index
    @products = []
    @@this_week.each_with_index do |id,index|
      puts "#{id}"
      @products[index] = Product.find(id)
    end
    if member_signed_in?
      @order = Order.create(:member => @current_member,
                          :cheap_beer => @count_cheap,
                          :class_beer => @count_class)
    else
      @order = Order.create(:cheap_beer => @count_cheap,
                            :class_beer => @count_class)
    end
  end

  def add_class    
    order = Order.find(params[:id])
    order.update_attribute(:class_beer, order.class_beer + 1)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Bottle Service</h1>

<% if member_signed_in? %>

  <div>Signed in as: <%= current_member.email %></div>
  <%= button_to "Not you?", destroy_member_session_path,:method => "delete" %>
  <%= button_to "Logout", destroy_member_session_path,:method => "delete" %>
  <% else %>
  <%= button_to "Sign In", new_member_session_path,:method => "get" %>
  <%= button_to "Sign Up", new_member_registration_path,:method => "get" %>
<% end %>

<% @products.each_with_index do |product,index| %>
<p>
  <strong>Title:</strong>
  <%= product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= product.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag product.image_url %>
</p>

<p>
  <strong>Info url:</strong>
  <%= link_to product.info_url %>
</p>

<p>
  <strong>Price:</strong>
  $<%= product.price %>
</p>

<%= text_field "#{product.title}", :method => "post" %>

<% end %>

<%= button_to "Checkout", order_path(:id) , :method => "post" %>