config/routes.rb
Bottleservice::Application.routes.draw do
  resources :orders

  devise_for :members
  devise_for :drivers
  resources :comments

  resources :drivers

  
  resources :products

  root 'orders#new'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :member
  belongs_to :driver  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  @@this_week = [1,2]
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @products = brew_week()
  end

  def brew_week
    products = []
    @@this_week.each_with_index do |id,index|
      puts "ID:#{id}"
      products[index] = Product.find(id)
    end
    return products
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    puts "ORDERPARAMS"
    @order = Order.new(order_params)
    puts "ORDER"
    puts "#{@order}"
    @order.driver = Driver.new(:stock_cheap => 2,
                               :stock_classy => 3,
                               :phone => 8675309)
    respond_to do |format|
      if @order.save
        if @order.member.nil?
          format.html { redirect_to new_member_registration_path, notice: 'Order was successfully created.' }
          format.json { render action: 'show', status: :created, location: @order }        
        else
          format.html { redirect_to @order, notice: 'Order was successfully created.' }
          format.json { render action: 'show', status: :created, location: @order }        
        end
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:cheap_beer, :class_beer, :member)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/.#_form.html.erb
zrfield@core.local.16699

app/views/orders/_form.html.erb
<%= form_for(@order, html: {multipart: true}) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<p>
  <strong>Title:</strong>
  <%= @products[0].title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @products[0].description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @products[0].image_url %>
</p>

<p>
  <strong>Info url:</strong>
  <%= link_to @products[0].info_url %>
</p>

<p>
  <strong>Price:</strong>
  $<%= @products[0].price %>
</p>

<%= f.number_field(:cheap_beer, in: 0.0..20.0, step: 1.0) %>


<p>
  <strong>Title:</strong>
  <%= @products[1].title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @products[1].description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @products[1].image_url %>
</p>

<p>
  <strong>Info url:</strong>
  <%= link_to @products[1].info_url %>
</p>

<p>
  <strong>Price:</strong>
  $<%= @products[1].price %>
</p>

<%= f.number_field(:class_beer, in: 0.0..20.0, step: 1.0) %>

<p>

</p>

  <%= f.submit %>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>Bottle Service</h1>

<% if member_signed_in? %>

  <div>Signed in as: <%= current_member.email %></div>
  <%= button_to "Not you?", destroy_member_session_path,:method => "delete" %>
  <%= button_to "Logout", destroy_member_session_path,:method => "delete" %>
  <% else %>
  <%= button_to "Sign In", new_member_session_path,:method => "get" %>
  <%= button_to "Sign Up", new_member_registration_path,:method => "get" %>
<% end %>

<%= render 'form' %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Order</h1>

<p><%= "Cheap:#{@order.cheap_beer} @ " %></p>
<p><%= "Class:#{@order.class_beer} @ " %></p>

<p><%= "Driver:#{@order.driver}"%> </p>
<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>